const incidentData = [
    { "value": "2ndalarmbrushfire", "Incident": "2nd Alarm Brush Fire" },
    { "value": "2ndalarmstructurefire", "Incident": "2nd Alarm Structure Fire" },
    { "value": "2ndalarmwildlandinterfacefire", "Incident": "2nd Alarm Wildland Interface Fire" },
    { "value": "airalert2", "Incident": "Air Alert 2" },
    { "value": "airalert3", "Incident": "Air Alert 3" },
    { "value": "airalert3offairport", "Incident": "Air Alert 3 Off-Airport" },
    { "value": "alarmreset", "Incident": "Alarm Reset" },
    { "value": "animalrescue", "Incident": "Animal Rescue" },
    { "value": "appliancefire", "Incident": "Appliance Fire" },
    { "value": "bbqgrillfire", "Incident": "BBQ Grill Fire" },
    { "value": "boatfire", "Incident": "Boat Fire" },
    { "value": "bombthreat", "Incident": "Bomb Threat" },
    { "value": "buildingcollapse", "Incident": "Building Collapse" },
    { "value": "carbonmonoxidealarmnosickparties", "Incident": "Carbon Monoxide Alarm, No Sick Parties" },
    { "value": "commercialcarrierfire", "Incident": "Commercial Carrier Fire" },
    { "value": "commercialfirealarm", "Incident": "Commercial Fire Alarm" },
    { "value": "commercialgasleak", "Incident": "Commercial Gas Leak" },
    { "value": "confinedspacerescue", "Incident": "Confined Space Rescue" },
    { "value": "corezero", "Incident": "Core Zero" },
    { "value": "divealert1", "Incident": "Dive Alert 1" },
    { "value": "divealert2", "Incident": "Dive Alert 2" },
    { "value": "divealert3", "Incident": "Dive Alert 3" },
    { "value": "dumpsterfire", "Incident": "Dumpster Fire" },
    { "value": "electricalhazard", "Incident": "Electrical Hazard" },
    { "value": "explosion", "Incident": "Explosion" },
    { "value": "extinguishedfire", "Incident": "Extinguished Fire" },
    { "value": "gaslinecut", "Incident": "Gas Line Cut" },
    { "value": "gunshotwound", "Incident": "Gunshot Wound" },
    { "value": "hazmatlevel1", "Incident": "Haz-Mat Level 1" },
    { "value": "hazmatlevel2", "Incident": "Haz-Mat Level 2" },
    { "value": "heavyrilaccident", "Incident": "Heavy Rail Accident" },
    { "value": "helicopterlandingzone", "Incident": "Helicopter Landing Zone" },
    { "value": "highwaymvaautovspedestrian", "Incident": "Highway MVA Auto vs. Pedestrian" },
    { "value": "highwaymvamotorcycle", "Incident": "Highway MVA Motorcycle" },
    { "value": "highwaymvarollover", "Incident": "Highway MVA Rollover" },
    { "value": "highwaymvawithinjuries", "Incident": "Highway MVA with Injuries" },
    { "value": "highwaymvawithunknowninjuries", "Incident": "Highway MVA with Unknown Injuries" },
    { "value": "highwayvehiclefire", "Incident": "Highway Vehicle Fire" },
    { "value": "illegalfire", "Incident": "Illegal Fire" },
    { "value": "knoxboxkeys", "Incident": "Knox Box Keys" },
    { "value": "largebrushfire", "Incident": "Large Brush Fire" },
    { "value": "largefuelspill", "Incident": "Large Fuel Spill" },
    { "value": "lawenforcementassist", "Incident": "Law Enforcement Assist" },
    { "value": "liftassist", "Incident": "Lift Assist" },
    { "value": "lightningstrikeinvestigation", "Incident": "Lightning Strike Investigation" },
    { "value": "linedowntransformerproblem", "Incident": "Line Down/Transformer Problem" },
    { "value": "lockoutnonemergent", "Incident": "Lock Out Non-Emergent" },
    { "value": "mcilarge", "Incident": "MCI Large" },
    { "value": "mcismall", "Incident": "MCI Small" },
    { "value": "medicalemergency", "Incident": "Medical Emergency" },
    { "value": "mvaautovspedestrian", "Incident": "MVA Auto vs. Pedestrian" },
    { "value": "mvaextrication", "Incident": "MVA Extrication" },
    { "value": "mvaheavyextrication", "Incident": "MVA Heavy Extrication" },
    { "value": "mvamediumextrication", "Incident": "MVA Medium Extrication" },
    { "value": "mvamotorcycle", "Incident": "MVA Motorcycle" },
    { "value": "mvanoninjury", "Incident": "MVA Non-Injury" },
    { "value": "mvarollover", "Incident": "MVA Rollover" },
    { "value": "mvainjuries", "Incident": "MVA with Injuries" },
    { "value": "mvaunknowninjuries", "Incident": "MVA with Unknown Injuries" },
    { "value": "odorinvestigation", "Incident": "Odor Investigation" },
    { "value": "odorinvestigationoutside", "Incident": "Odor Investigation Outside" },
    { "value": "oilwellfire", "Incident": "Oil Well Fire" },
    { "value": "otheragencyassist", "Incident": "Other Agency Assist" },
    { "value": "outsidefire", "Incident": "Outside Fire" },
    { "value": "partiestrappedinelevator", "Incident": "Parties Trapped in Elevator" },
    { "value": "penetratingtrauma", "Incident": "Penetrating Trauma" },
    { "value": "propanetankfire", "Incident": "Propane Tank Fire" },
    { "value": "publicassist", "Incident": "Public Assist" },
    { "value": "reportedstructurefire", "Incident": "Reported Structure Fire" },
    { "value": "residentialfirealarm", "Incident": "Residential Fire Alarm" },
    { "value": "residentialgasleak", "Incident": "Residential Gas Leak" },
    { "value": "roperescue", "Incident": "Rope Rescue" },
    { "value": "smallbrushfire", "Incident": "Small Brush Fire" },
    { "value": "smallfuelspill", "Incident": "Small Fuel Spill" },
    { "value": "smokeinvestigationinside", "Incident": "Smoke Investigation Inside" },
    { "value": "smokeinvestigationoutside", "Incident": "Smoke Investigation Outside" },
    { "value": "stabbing", "Incident": "Stabbing" },
    { "value": "standbyblue", "Incident": "Standby Blue" },
    { "value": "strandedmotorist", "Incident": "Stranded Motorist" },
    { "value": "trainfire", "Incident": "Train Fire" },
    { "value": "trenchcollapse", "Incident": "Trench Collapse" },
    { "value": "unknownfire", "Incident": "Unknown Fire" },
    { "value": "vehiclefire", "Incident": "Vehicle Fire" },
    { "value": "washdownladderrequest", "Incident": "Wash Down or Ladder Request" },
    { "value": "waterproblem", "Incident": "Water Problem" },
    { "value": "watershutoff", "Incident": "Water Shutoff" },
    { "value": "waterflowalarm", "Incident": "Waterflow Alarm" },
    { "value": "wildlandinterfacefire", "Incident": "Wildland Interface Fire" },
    { "value": "workingcommercialfire", "Incident": "Working Commercial Fire" },
    { "value": "workingmultifamilyfire", "Incident": "Working Multi-Family Fire" },
    { "value": "workingresidentialfire", "Incident": "Working Residential Fire" }
  ];

  const selectElement = document.getElementById("options");

  incidentData.forEach(item => {
    const optionElement = document.createElement("option");
    optionElement.value = item.value;
    optionElement.textContent = item.Incident;
    selectElement.appendChild(optionElement);
  });