const incidentData = [
    { "value": "2ndalarmbrushfire", "Incident": "2nd Alarm Brush Fire", "Response": "(+) 1BRE 4BR 2TN 2BC 1SAF OPS14" },
    { "value": "2ndalarmstructurefire", "Incident": "2nd Alarm Structure Fire", "Response": "(+) 4E 1ARL 1R 2M 2BC 1SAF OPS14" },
    { "value": "2ndalarmwildlandinterfacefire", "Incident": "2nd Alarm Wildland Interface Fire", "Response": "(+) 3E 3BR 3TN 1M 1DC 1BC 1SAF OPS14" },
    { "value": "airalert2", "Incident": "Air Alert 2", "Response": "RED1 RED2 RED3 1M 1BC 1SAF KAPAOPS" },
    { "value": "airalert3", "Incident": "Air Alert 3", "Response": "RED1 RED2 RED3 2E 2M 1BC 1SAF 1MED PIO KAPAOPS" },
    { "value": "airalert3offairport", "Incident": "Air Alert 3 Off-Airport", "Response": "1RED 1ARL 2E 2M 2BC 1SAF 1MED PIO OPS" },
    { "value": "alarmreset", "Incident": "Alarm Reset", "Response": "1SPN" },
    { "value": "animalrescue", "Incident": "Animal Rescue", "Response": "1SPN" },
    { "value": "appliancefire", "Incident": "Appliance Fire", "Response": "1SPN" },
    { "value": "bbqgrillfire", "Incident": "BBQ Grill Fire", "Response": "1SPN" },
    { "value": "boatfire", "Incident": "Boat Fire", "Response": "1SPN" },
    { "value": "bombthreat", "Incident": "Bomb Threat", "Response": "1SPN, 1M, 1BC" },
    { "value": "buildingcollapse", "Incident": "Building Collapse", "Response": "1R 1H 1COL 1ARL 2E 3M 2BC 1SAF 1MED PIO OPS" },
    { "value": "carbonmonoxidealarmnosickparties", "Incident": "Carbon Monoxide Alarm, No Sick Parties", "Response": "1SPN" },
    { "value": "commercialcarrierfire", "Incident": "Commercial Carrier Fire", "Response": "2SPN" },
    { "value": "commercialfirealarm", "Incident": "Commercial Fire Alarm", "Response": "1SPN" },
    { "value": "commercialgasleak", "Incident": "Commercial Gas Leak", "Response": "2SPN 1BC OPS" },
    { "value": "confinedspacerescue", "Incident": "Confined Space Rescue", "Response": "1R 1H 3M 1ARL 2E 2BC 1SAF 1MED PIO OPS" },
    { "value": "corezero", "Incident": "Core Zero", "Response": "1SPN 1M 1BC/MED" },
    { "value": "divealert1", "Incident": "Dive Alert 1", "Response": "1DIV 1SPN 1M 1BC 1SAF OPS" },
    { "value": "divealert2", "Incident": "Dive Alert 2", "Response": "1DIV 1BC OPS" },
    { "value": "divealert3", "Incident": "Dive Alert 3", "Response": "2DIV 2SPN 2M 2BC 1SAF PIO OPS" },
    { "value": "dumpsterfire", "Incident": "Dumpster Fire", "Response": "1SPN" },
    { "value": "electricalhazard", "Incident": "Electrical Hazard", "Response": "1SPN" },
    { "value": "explosion", "Incident": "Explosion", "Response": "1BC 1SAF 2E 1ARL 1M OPS" },
    { "value": "extinguishedfire", "Incident": "Extinguished Fire", "Response": "1SPN" },
    { "value": "gaslinecut", "Incident": "Gas Line Cut", "Response": "2SPN 1BC OPS" },
    { "value": "gunshotwound", "Incident": "Gunshot Wound", "Response": "1SPN 1M 1BC/MED" },
    { "value": "hazmatlevel1", "Incident": "Haz-Mat Level 1", "Response": "1H 1M 1SPN 1BC 1SAF BU OPS" },
    { "value": "hazmatlevel2", "Incident": "Haz-Mat Level 2", "Response": "2H 2M 1SPN 1BC 1SAF BU PIO RH OPS" },
    { "value": "heavyrrailaccident", "Incident": "Heavy Rail Accident", "Response": "1R 1H 3M 1ARL 2E 2BC 1SAF 1MED PIO OPS" },
    { "value": "helicopterlandingzone", "Incident": "Helicopter Landing Zone", "Response": "1SPN" },
    { "value": "highwaymvaautovspedestrian", "Incident": "Highway MVA Auto vs. Pedestrian", "Response": "2SPN 1M" },
    { "value": "highwaymvamotorcycle", "Incident": "Highway MVA Motorcycle", "Response": "2SPN 1M" },
    { "value": "highwaymvarollover", "Incident": "Highway MVA Rollover", "Response": "2SPN 1M" },
    { "value": "highwaymvawithinjuries", "Incident": "Highway MVA with Injuries", "Response": "2SPN 1M" },
    { "value": "highwaymvawithunknowninjuries", "Incident": "Highway MVA with Unknown Injuries", "Response": "2SPN 1M" },
    { "value": "highwayvehiclefire", "Incident": "Highway Vehicle Fire", "Response": "2SPN 1M" },
    { "value": "illegalfire", "Incident": "Illegal Fire", "Response": "1SPN" },
    { "value": "knoxboxkeys", "Incident": "Knox Box Keys", "Response": "1SPN" },
    { "value": "largebrushfire", "Incident": "Large Brush Fire", "Response": "2BRE 2E 2BR 1M 1TN 2BC 1SAF 1MED BU PIO IDT RH OPS" },
    { "value": "largefuelspill", "Incident": "Large Fuel Spill", "Response": "1H 1FOAM 2E 1M 1BC 1SAF BU PIO OPS" },
    { "value": "lawenforcementassist", "Incident": "Law Enforcement Assist", "Response": "1SPN, 1M, 1BC" },
    { "value": "liftassist", "Incident": "Lift Assist", "Response": "1SPN" },
    { "value": "lightningstrikeinvestigation", "Incident": "Lightning Strike Investigation", "Response": "2SPN" },
    { "value": "linedowntransformerproblem", "Incident": "Line Down/Transformer Problem", "Response": "1SPN" },
    { "value": "lockoutnonemergent", "Incident": "Lock Out Non-Emergent", "Response": "1SPN" },
    { "value": "mcilarge", "Incident": "MCI Large", "Response": "(+) 5SPN 5M 1BC 1SAF OPS14" },
    { "value": "mcismall", "Incident": "MCI Small", "Response": "5SPN 5M 1BC 1SAF 1MED OPS" },
    { "value": "medicalemergency", "Incident": "Medical Emergency", "Response": "1SPN 1M" },
    { "value": "mvaautovspedestrian", "Incident": "MVA Auto vs. Pedestrian", "Response": "1SPN 1M" },
    { "value": "mvaextrication", "Incident": "MVA Extrication", "Response": "1ARL 1E 2M 1BC 1SAF OPS" },
    { "value": "mvheavyextrication", "Incident": "MVA Heavy Extrication", "Response": "2R 1ARL 2E 2M 2BC 1SAF 1MED OPS" },
    { "value": "mvamediumextrication", "Incident": "MVA Medium Extrication", "Response": "1R 1ARL 2E 2M 2BC 1SAF 1MED OPS" },
    { "value": "mvamotorcycle", "Incident": "MVA Motorcycle", "Response": "1SPN 1M" },
    { "value": "mvanoninury", "Incident": "MVA Non-Injury", "Response": "1SPN" },
    { "value": "mvarollover", "Incident": "MVA Rollover", "Response": "1SPN 1M" },
    { "value": "mvawithinjuries", "Incident": "MVA with Injuries", "Response": "1SPN 1M" },
    { "value": "mvawithunknowninjuries", "Incident": "MVA with Unknown Injuries", "Response": "1SPN 1M" },
    { "value": "odorinvestigation", "Incident": "Odor Investigation", "Response": "1SPN" },
    { "value": "odorinvestigationoutside", "Incident": "Odor Investigation Outside", "Response": "1SPN" },
    { "value": "oilwellfire", "Incident": "Oil Well Fire", "Response": "2SPN 1BC OPS" },
    { "value": "otheragencyassist", "Incident": "Other Agency Assist", "Response": "1SPN, 1M, 1BC" },
    { "value": "outsidefire", "Incident": "Outside Fire", "Response": "1SPN" },
    { "value": "partiestrappedinelevator", "Incident": "Parties Trapped in Elevator", "Response": "1SPN" },
    { "value": "penetratingtrauma", "Incident": "Penetrating Trauma", "Response": "1SPN 1M 1BC/MED" },
    { "value": "propaneankfire", "Incident": "Propane Tank Fire", "Response": "1BC 1SAF 2E 1ARL 1M OPS" },
    { "value": "publicassist", "Incident": "Public Assist", "Response": "1SPN" },
    { "value": "reportedstructurefire", "Incident": "Reported Structure Fire", "Response": "1BC 1SAF 2E 1ARL 1M OPS" },
    { "value": "residentialfirealarm", "Incident": "Residential Fire Alarm", "Response": "1SPN" },
    { "value": "residentialgasleak", "Incident": "Residential Gas Leak", "Response": "1SPN" },
    { "value": "roperescue", "Incident": "Rope Rescue", "Response": "1R 1ARL 2E 2M 2BC 1SAF PIO OPS" },
    { "value": "smallbrushfire", "Incident": "Small Brush Fire", "Response": "1E 1BSH 1BC OPS" },
    { "value": "smallfuelspill", "Incident": "Small Fuel Spill", "Response": "1SPN" },
    { "value": "smokeinvestigationinside", "Incident": "Smoke Investigation Inside", "Response": "2SPN 1BC OPS" },
    { "value": "smokeinvestigationoutside", "Incident": "Smoke Investigation Outside", "Response": "1SPN" },
    { "value": "stabbing", "Incident": "Stabbing", "Response": "1SPN 1M 1BC/MED" },
    { "value": "standbyblue", "Incident": "Standby Blue", "Response": "1SPN 1M 1BC 1SAF BLUOPS" },
    { "value": "strandedmotorist", "Incident": "Stranded Motorist", "Response": "1SPN" },
    { "value": "trainfire", "Incident": "Train Fire", "Response": "1H 1FOAM 2E 1ARL 2M 2TN 2BC 1SAF PIO BU OPS" },
    { "value": "trenchcollapse", "Incident": "Trench Collapse", "Response": "1R 1H 1COL 1ARL 2E 3M 2BC 1SAF 1MED PIO OPS" },
    { "value": "unknownfire", "Incident": "Unknown Fire", "Response": "1SPN" },
    { "value": "vehiclefire", "Incident": "Vehicle Fire", "Response": "1SPN 1M" },
    { "value": "washdownorladderrequest", "Incident": "Wash Down or Ladder Request", "Response": "1SPN" },
    { "value": "waterproblem", "Incident": "Water Problem", "Response": "1SPN" },
    { "value": "watershutoff", "Incident": "Water Shutoff", "Response": "1SPN" },
    { "value": "waterflowalarm", "Incident": "Waterflow Alarm", "Response": "2SPN" },
    { "value": "wildlandinterfacefire", "Incident": "Wildland Interface Fire", "Response": "2BRE 2E 2BR 2M 2TN 2BC 1DC 1SAF 1MED BU PIO IDT IST RH OPS" },
    { "value": "workingcommercialfire", "Incident": "Working Commercial Fire", "Response": "4E 2ARL 1R 2M 2BC 1SAF 1MED BU PIO IDT RH OPS" },
    { "value": "workingmultifamilyfire", "Incident": "Working Multi-Family Fire", "Response": "4E 2ARL 2M 2BC 1SAF 1MED BU PIO IDT RH OPS" },
    { "value": "workingresidentialfire", "Incident": "Working Residential Fire", "Response": "4E 1ARL 2M 2BC 1SAF 1MED BU OPS" }
];
